models/UserIdentity.php
<?php
namespace app\models;

use yii\web\IdentityInterface;

class UserIdentity extends UserRecord implements IdentityInterface
{
    /**
     * Finds an identity by the given ID.
     * @param string|int $id the ID to be looked for
     * @return IdentityInterface|null the identity object that matches the given ID.
     * Null should be returned if such an identity cannot be found
     * or the identity is not in an active state (disabled, deleted, etc.)
     */
    public static function findIdentity($id)
    {
       return static::findOne($id);
    }

    /**
     * Finds an identity by the given token.
     * @param mixed $token the token to be looked for
     * @param mixed $type the type of the token. The value of this parameter depends on the implementation.
     * For example, [[\yii\filters\auth\HttpBearerAuth]] will set this parameter to be `yii\filters\auth\HttpBearerAuth`.
     * @return IdentityInterface|null the identity object that matches the given token.
     * Null should be returned if such an identity cannot be found
     * or the identity is not in an active state (disabled, deleted, etc.)
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        // TODO: Implement findIdentityByAccessToken() method.
    }

    /**
     * Returns an ID that can uniquely identify a user identity.
     * @return string|int an ID that uniquely identifies a user identity.
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns a key that can be used to check the validity of a given identity ID.
     *
     * The key should be unique for each individual user, and should be persistent
     * so that it can be used to check the validity of the user identity.
     *
     * The space of such keys should be big enough to defeat potential identity attacks.
     *
     * This is required if [[User::enableAutoLogin]] is enabled. The returned key will be stored on the
     * client side as a cookie and will be used to authenticate user even if PHP session has been expired.
     *
     * Make sure to invalidate earlier issued authKeys when you implement force user logout, password change and
     * other scenarios, that require forceful access revocation for old sessions.
     *
     * @return string a key that is used to check the validity of a given identity ID.
     * @see validateAuthKey()
     */
    public function getAuthKey()
    {
        // TODO: Implement getAuthKey() method.
    }

    /**
     * Validates the given auth key.
     *
     * This is required if [[User::enableAutoLogin]] is enabled.
     * @param string $authKey the given auth key
     * @return bool whether the given auth key is valid.
     * @see getAuthKey()
     */
    public function validateAuthKey($authKey)
    {
        // TODO: Implement validateAuthKey() method.
    }
}

models/UserJoinForm.php
<?php
namespace app\models;

use yii\base\Model;

class UserJoinForm extends Model
{
    public $name;
    public $email;
    public $password;
    public $rePassword;

    public function rules ()
    {
        return
        [
            [['name','email','password','rePassword'], 'required']
        ];
    }
}

models/UserRecord.php
<?php
namespace app\models;
use Faker\Factory;
use yii\db\ActiveRecord;

class UserRecord extends ActiveRecord
{
    public static function tableName() {
        return 'user';
    }

    public function setTestUser()
    {
        $faker = Factory::create();
        $this->name = $faker->name;
        $this->email = $faker->email;
        $this->passhash = $faker->password;
        $this->status = $faker->randomDigit;
    }
}

controllers/SiteController.php
<?php
namespace app\controllers;

use yii\web\Controller;

class SiteController extends Controller
    /**
     * Контроллер index.php с подключенным модулем дебага и
     * логами вывода сообщений: debug, warning, error.
     */
{
    public function actionIndex()
    {
        \Yii::debug('Hello from action index', 'test');
        \Yii::warning('warning test');
        \Yii::error('On exception');
        return  $this->render('index');
    }

    public function actionJoin() {
        return $this->render('join');
    }

    public function actionLogin() {
        return $this->render('login');
    }
}

controllers/UserController.php
<?php
namespace app\controllers;

use app\models\UserIdentity;
use app\models\UserJoinForm;
use app\models\UserRecord;
use Yii;
use yii\web\Controller;

class UserController extends Controller
    /**
     * Контроллер index.php с подключенным модулем дебага и
     * логами вывода сообщений: debug, warning, error.
     */
{
    public function actionJoin() {
//        $userRecord = new UserRecord();
//        $userRecord->setTestUser();
//        $userRecord->save();
        $userJoinForm = new UserJoinForm();
        return $this->render('join', compact('userJoinForm'));
    }

    public function actionLogin() {
//        $uid = UserIdentity::findIdentity(mt_rand(0, 58));
//        Yii::$app->user->login($uid);
        return $this->render('login');
    }

    public function actionLogout() {
        Yii::$app->user->logout();
        return$this->redirect("/");
    }
}

views/layouts/main.php
<?php

use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;

$this->beginPage();
?>
<html lang="eng">
<head>
    <title> Video school</title>
    <?php $this->head(); ?>

</head>

<body>
<?php $this->beginBody(); ?>
<?php
NavBar::begin([
        'brandLabel' => 'WEB DEVELOPERS',
        'brandUrl' => Yii::$app->homeUrl,
    'options' => [
            'class' => 'navbar-default navbar-fixed-top'
    ]
]);
/**
 * Асоциативнй массив  с ключами лейблами и значениями ссылок
 * Представления для гостя иначе для залогиненного user
 */
if (Yii::$app->user->isGuest) {
    $items = [
        ['label' => 'Join', 'url' => ['/user/join']],
        ['label' => 'Login', 'url' => ['/user/login']]
    ];
} else {
    try {
        $items = [
            ['label' => Yii::$app->user->getIdentity()->name],
            ['label' => 'Logout', 'url' => ['/user/logout']]
        ];
    } catch (Throwable $e) {
        $e->getTraceAsString();
    }
}
;
/**
 * Виджет рендера бокового меню логина
 * @throws Exception
 * @return string the rendering result of the widget
 */
try {
    echo Nav::widget([
        'options' => [
            'class' => 'navbar-nav navbar-right'],
        'items' => $items
    ]);
} catch (Exception $exception) {
    $exception->getTraceAsString();
}
NavBar::end();
?>
<div class="container" style="margin-top: 60px">
<?= $content ?>
</div>
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>

views/site/index.php
<h1>Guest book</h1>
Welcome guest!

views/site/join.php
<h1>Join us</h1>

Fill register form

views/site/login.php
<h1>Log in</h1>

Enter your e-mail and password

views/user/join.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>
<div class="panel-danger">
    <div class="panel-heading">
        <h1>Join us</h1>
    </div>
    <div class="panel-body">
        Fill register form<br/><br/>
        <?php
        $form = ActiveForm::begin(['id' => 'user-join-form']); ?>
        <?= $form ->field($userJoinForm, 'name') ?>
        <?= $form ->field($userJoinForm, 'email') ?>
        <?= $form ->field($userJoinForm, 'password')->passwordInput()?>
        <?= $form ->field($userJoinForm, 'rePassword')->passwordInput() ?>
        <?= Html::submitButton('Create',
            ['class' => 'btn btn-danger']) ?>
<?php ActiveForm::end(); ?>
    </div>
</div>

views/user/login.php
<div class="panel-info">
    <div class="panel-heading">
        <h1>Log in</h1>
    </div>
    <div class="panel-body">
        Enter you data<br/><br/>
        email<br/>
        password<br/>
    </div>
    [enter]
</div>